// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface GreenToken$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "GreenToken";
  readonly sourceName: "contracts/GreenToken.sol";
  readonly abi: [];
  readonly bytecode: "0x6080604052348015600e575f5ffd5b50603e80601a5f395ff3fe60806040525f5ffdfea264697066735822122086aba11174328e17e5da81d18d0bb576e946e1fbb646e9c1e45aeeacf2a2d0f764736f6c634300081c0033";
  readonly deployedBytecode: "0x60806040525f5ffdfea264697066735822122086aba11174328e17e5da81d18d0bb576e946e1fbb646e9c1e45aeeacf2a2d0f764736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/GreenToken.sol";
  readonly buildInfoId: "solc-0_8_28-791859e501f0570321ff58bd34508c5426b05139";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["GreenToken"]: GreenToken$Type;
    ["contracts/GreenToken.sol:GreenToken"]: GreenToken$Type;
  }
}