// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface DocumentRegistry$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "DocumentRegistry";
  readonly sourceName: "contracts/DocumentRegistry.sol";
  readonly abi: [];
  readonly bytecode: "0x6080604052348015600e575f5ffd5b50603e80601a5f395ff3fe60806040525f5ffdfea2646970667358221220e2b6a721312aa9721496d1267f3779523038680ded79366381210e5622d82ba564736f6c634300081c0033";
  readonly deployedBytecode: "0x60806040525f5ffdfea2646970667358221220e2b6a721312aa9721496d1267f3779523038680ded79366381210e5622d82ba564736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/DocumentRegistry.sol";
  readonly buildInfoId: "solc-0_8_28-791859e501f0570321ff58bd34508c5426b05139";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["DocumentRegistry"]: DocumentRegistry$Type;
    ["contracts/DocumentRegistry.sol:DocumentRegistry"]: DocumentRegistry$Type;
  }
}